name: Deploy

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp SpringBootUserManagement-0.0.1-SNAPSHOT.jar SpringBootUserManagement-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@v2
        with:
          name: SpringBootUserManagement
          path: SpringBootUserManagement-${{ github.sha }}.jar
